# Configuration File for Travis-CI

language: python
python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-scipy

install: pip install -r vis/travis_requirements.txt

script:  coverage run run_tests.py

after_success: coveralls
