# Configuration File for Travis-CI
sudo: false
addons:
 apt:
  packages:
   - liblapack-dev
   - gfortran
language: python
python:
  - "2.7"
  - "3.4"
install: pip install -r vis/travis_requirements.txt
script:  coverage run run_tests.py
after_success: coveralls